### ISSUE TITLE
Description of read opcode for versions 1-4

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/Z-Machine-Standard#76]
From this discussion https://intfiction.org/t/lectrote-zvm-sread-text-parse/49123

It seems like this paragraph from section 15 is wrong, and should say "plus" rather than "minus":

> In Versions 1 to 4, byte 0 of the text-buffer should initially contain the maximum number of letters which can be typed, minus 1 (the interpreter should not accept more than this).

**Comment by DFillmore** [comment]
I suggest changing this to 

> In Versions 1 to 4, byte 0 of the text-buffer should initially contain the maximum number of letters which can be 
> typed (the interpreter should not accept more than this), plus 1 (for the zero terminator).
